version: "3.8"

services:
  mongo:
    image: mongo:4.4.6-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=amazon-root
      - MONGO_INITDB_ROOT_PASSWORD=amazon-root
    restart: always
    hostname: mongo
    networks:
      - amazon
    ports:
      - 27017:27017
    working_dir: /data
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume:

networks:
  amazon:
